apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubox.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kubox.name" . }}
    helm.sh/chart: {{ include "kubox.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  authorized_keys: |-
{{ .Values.kubox.authorizedKeys | indent 4 }}
