{{- if .Values.kubox.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubox.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kubox.name" . }}
    helm.sh/chart: {{ include "kubox.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.kubox.password | b64enc }}
{{- end }}
