apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubox.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kubox.name" . }}
    helm.sh/chart: {{ include "kubox.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ssh
      port: {{ .Values.service.port }}
      targetPort: ssh
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "kubox.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
